schema:
  - 'src/main/resources/graphql/schema.graphqls'
  - 'src/main/resources/graphql/model.graphqls'
  - 'src/main/resources/graphql/dto.graphqls'

documents:
  - 'src/test/resources/graphql-test/**/*.graphql'

extensions:
  endpoints:
    GraphQL Endpoint:
      url: 'http://localhost:9090/graphql'
      headers:
        user-agent: 'JS GraphQL'
      introspect: false
